[project]
name = "data-lakehouse-olist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.93",
    "kagglehub>=0.3.6",
    "python-dotenv>=1.0.1",
]
